security:
  basic:
    enabled: false
 user:
   password: password

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG


spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct
